// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Theatre.Api.Data;

#nullable disable

namespace Theatre.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805134427_AddOperationalEvents")]
    partial class AddOperationalEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Theatre.Api.Models.AdminActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AdminDisplayName")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int?>("AdminUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Summary")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("AdminActivities");
                });

            modelBuilder.Entity("Theatre.Api.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("Theatre.Api.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("Theatre.Api.Models.CreditType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DisplayOrder");

                    b.ToTable("CreditTypes");
                });

            modelBuilder.Entity("Theatre.Api.Models.CreditTypeTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreditTypeId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("CreditTypeId", "LanguageId")
                        .IsUnique();

                    b.ToTable("CreditTypeTranslations");
                });

            modelBuilder.Entity("Theatre.Api.Models.GalleryAlbum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlbumType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("CoverMediaAssetId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisibleInGeneralGallery")
                        .HasColumnType("bit");

                    b.Property<int?>("NewsArticleId")
                        .HasColumnType("int");

                    b.Property<int?>("PitfEditionId")
                        .HasColumnType("int");

                    b.Property<int?>("ShowId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AlbumType");

                    b.HasIndex("CoverMediaAssetId");

                    b.HasIndex("EventDate");

                    b.HasIndex("IsPublished");

                    b.HasIndex("IsVisibleInGeneralGallery");

                    b.HasIndex("NewsArticleId");

                    b.HasIndex("PitfEditionId");

                    b.HasIndex("ShowId");

                    b.ToTable("GalleryAlbums", t =>
                        {
                            t.HasCheckConstraint("CK_GalleryAlbums_AlbumType_Parent", "([AlbumType] = 'General' AND [ShowId] IS NULL AND [NewsArticleId] IS NULL AND [PitfEditionId] IS NULL) OR ([AlbumType] = 'Show' AND [ShowId] IS NOT NULL AND [NewsArticleId] IS NULL AND [PitfEditionId] IS NULL) OR ([AlbumType] = 'NewsArticle' AND [ShowId] IS NULL AND [NewsArticleId] IS NOT NULL AND [PitfEditionId] IS NULL) OR ([AlbumType] = 'PitfEdition' AND [ShowId] IS NULL AND [NewsArticleId] IS NULL AND [PitfEditionId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Theatre.Api.Models.GalleryAlbumMedia", b =>
                {
                    b.Property<int>("GalleryAlbumId")
                        .HasColumnType("int");

                    b.Property<int>("MediaAssetId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsCover")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.HasKey("GalleryAlbumId", "MediaAssetId");

                    b.HasIndex("GalleryAlbumId");

                    b.HasIndex("MediaAssetId");

                    b.HasIndex("GalleryAlbumId", "DisplayOrder");

                    b.HasIndex("MediaAssetId", "IsFeatured");

                    b.ToTable("GalleryAlbumMedia");
                });

            modelBuilder.Entity("Theatre.Api.Models.GalleryAlbumTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<int>("GalleryAlbumId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.HasKey("Id");

                    b.HasIndex("GalleryAlbumId", "LanguageId")
                        .IsUnique();

                    b.HasIndex("LanguageId", "Slug")
                        .IsUnique();

                    b.ToTable("GalleryAlbumTranslations");
                });

            modelBuilder.Entity("Theatre.Api.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("[IsDefault] = 1");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "sq",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Albanian"
                        },
                        new
                        {
                            Id = 2,
                            Code = "en",
                            IsActive = true,
                            IsDefault = false,
                            Name = "English"
                        });
                });

            modelBuilder.Entity("Theatre.Api.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GoogleMapsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Theatre.Api.Models.LocationTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LocationId", "LanguageId")
                        .IsUnique();

                    b.ToTable("LocationTranslations");
                });

            modelBuilder.Entity("Theatre.Api.Models.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PhotographerCredit")
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<DateTimeOffset?>("TakenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("FileUrl");

                    b.HasIndex("IsActive");

                    b.HasIndex("UploadedAt");

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("Theatre.Api.Models.MediaAssetTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("MediaAssetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("MediaAssetId", "LanguageId")
                        .IsUnique();

                    b.ToTable("MediaAssetTranslations");
                });

            modelBuilder.Entity("Theatre.Api.Models.NewsArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArticleType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("CardThumbnailMediaAssetId")
                        .HasColumnType("int");

                    b.Property<int?>("CoverMediaAssetId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExternalSourceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ArticleType");

                    b.HasIndex("CardThumbnailMediaAssetId");

                    b.HasIndex("CoverMediaAssetId");

                    b.HasIndex("IsFeatured");

                    b.HasIndex("IsPublished");

                    b.HasIndex("PublishedAt");

                    b.ToTable("NewsArticles", t =>
                        {
                            t.HasCheckConstraint("CK_NewsArticles_ArticleType_ExternalUrl", "([ArticleType] = 'Authored' AND [ExternalUrl] IS NULL) OR ([ArticleType] = 'External' AND [ExternalUrl] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Theatre.Api.Models.NewsArticleTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<int>("NewsArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId", "Slug")
                        .IsUnique();

                    b.HasIndex("NewsArticleId", "LanguageId")
                        .IsUnique();

                    b.ToTable("NewsArticleTranslations");
                });

            modelBuilder.Entity("Theatre.Api.Models.NewsExternalLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("NewsArticleId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SourceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Url");

                    b.HasIndex("NewsArticleId", "DisplayOrder");

                    b.ToTable("NewsExternalLinks");
                });

            modelBuilder.Entity("Theatre.Api.Models.NewsletterSubscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PreferredLanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Source")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("SubscribedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UnsubscribedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("SubscribedAt");

                    b.ToTable("NewsletterSubscribers");
                });

            modelBuilder.Entity("Theatre.Api.Models.OperationalEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EventType", "CreatedAt");

                    b.ToTable("OperationalEvents");
                });

            modelBuilder.Entity("Theatre.Api.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int?>("ProfileMediaAssetId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.HasIndex("ProfileMediaAssetId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Theatre.Api.Models.PersonTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("ProfessionalTitle")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PersonId", "LanguageId")
                        .IsUnique();

                    b.ToTable("PersonTranslations");
                });

            modelBuilder.Entity("Theatre.Api.Models.PitfEdition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoverMediaAssetId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DestinationUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("EditionNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int?>("LogoMediaAssetId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoverMediaAssetId");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("LogoMediaAssetId");

                    b.HasIndex("Year");

                    b.HasIndex("Year", "EditionNumber")
                        .IsUnique();

                    b.ToTable("PitfEditions");
                });

            modelBuilder.Entity("Theatre.Api.Models.PitfEditionTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<int>("PitfEditionId")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId", "Slug")
                        .IsUnique();

                    b.HasIndex("PitfEditionId", "LanguageId")
                        .IsUnique();

                    b.ToTable("PitfEditionTranslations");
                });

            modelBuilder.Entity("Theatre.Api.Models.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeRecommendation")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("FeaturedMediaAssetId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("OriginalLanguage")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("PosterMediaAssetId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("PremiereDate")
                        .HasColumnType("date");

                    b.Property<int?>("ProductionYear")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ShowCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TrailerUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("UseLocalGalleryFallback")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("FeaturedMediaAssetId");

                    b.HasIndex("PosterMediaAssetId");

                    b.HasIndex("PremiereDate");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("ShowCategoryId");

                    b.HasIndex("Status");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("Theatre.Api.Models.ShowCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.ToTable("ShowCategories");
                });

            modelBuilder.Entity("Theatre.Api.Models.ShowCategoryTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("ShowCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId", "Slug")
                        .IsUnique();

                    b.HasIndex("ShowCategoryId", "LanguageId")
                        .IsUnique();

                    b.ToTable("ShowCategoryTranslations");
                });

            modelBuilder.Entity("Theatre.Api.Models.ShowCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CharacterName")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("CreditTypeId")
                        .HasColumnType("int");

                    b.Property<string>("CustomRoleEn")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("CustomRoleSq")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("ShowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreditTypeId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ShowId", "DisplayOrder");

                    b.ToTable("ShowCredits");
                });

            modelBuilder.Entity("Theatre.Api.Models.ShowPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EndDateTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Hall")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("ShowId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartDateTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TicketUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IsPublished");

                    b.HasIndex("LocationId");

                    b.HasIndex("ShowId");

                    b.HasIndex("StartDateTimeUtc");

                    b.HasIndex("Status");

                    b.ToTable("ShowPerformances");
                });

            modelBuilder.Entity("Theatre.Api.Models.ShowTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int>("ShowId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId", "Slug")
                        .IsUnique();

                    b.HasIndex("ShowId", "LanguageId")
                        .IsUnique();

                    b.ToTable("ShowTranslations");
                });

            modelBuilder.Entity("Theatre.Api.Models.StaticPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("FeaturedMediaAssetId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("MapEmbedUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MapLinkUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PageKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("ParallaxMediaAssetId")
                        .HasColumnType("int");

                    b.Property<int?>("SocialSharingMediaAssetId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FeaturedMediaAssetId");

                    b.HasIndex("PageKey")
                        .IsUnique();

                    b.HasIndex("ParallaxMediaAssetId");

                    b.HasIndex("SocialSharingMediaAssetId");

                    b.ToTable("StaticPages");
                });

            modelBuilder.Entity("Theatre.Api.Models.StaticPageTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("QuoteAuthor")
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("QuoteText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("StatOneLabel")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("StatOneValue")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("StatThreeLabel")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("StatThreeValue")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("StatTwoLabel")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("StatTwoValue")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("StaticPageId")
                        .HasColumnType("int");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId", "Slug")
                        .IsUnique();

                    b.HasIndex("StaticPageId", "LanguageId")
                        .IsUnique();

                    b.ToTable("StaticPageTranslations");
                });

            modelBuilder.Entity("Theatre.Api.Models.TheatreInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutButtonLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("AboutPreviewMediaAssetId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("FaviconMediaAssetId")
                        .HasColumnType("int");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<int?>("HeroBackgroundMediaAssetId")
                        .HasColumnType("int");

                    b.Property<bool>("HeroIsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("InstagramUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LatestNewsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<int?>("LogoMediaAssetId")
                        .HasColumnType("int");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("NavigationConfigurationJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerformancesCount")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PitfDestinationUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("PitfFeatureIsVisible")
                        .HasColumnType("bit");

                    b.Property<int?>("PitfFeatureMediaAssetId")
                        .HasColumnType("int");

                    b.Property<string>("PitfPageButtonUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PitfPageMediaAssetId")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryButtonLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("ReservationBannerIsVisible")
                        .HasColumnType("bit");

                    b.Property<int?>("ReservationBannerMediaAssetId")
                        .HasColumnType("int");

                    b.Property<string>("ReservationUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SocialSharingMediaAssetId")
                        .HasColumnType("int");

                    b.Property<int>("SpectatorsCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AboutPreviewMediaAssetId");

                    b.HasIndex("FaviconMediaAssetId");

                    b.HasIndex("HeroBackgroundMediaAssetId");

                    b.HasIndex("LogoMediaAssetId");

                    b.HasIndex("PitfFeatureMediaAssetId");

                    b.HasIndex("PitfPageMediaAssetId");

                    b.HasIndex("ReservationBannerMediaAssetId");

                    b.HasIndex("SocialSharingMediaAssetId");

                    b.ToTable("TheatreInformation");
                });

            modelBuilder.Entity("Theatre.Api.Models.TheatreInformationTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutButtonText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AboutFull")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutShort")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("AboutTitle")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("AddressDisplayText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FooterCopyrightText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("HeroButtonText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HeroSlogan")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("HeroSupportingText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("PitfFeatureButtonText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PitfFeatureTitle")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("PitfPageButtonText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PitfPageDescription")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("PitfPageTitle")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("PitfShortDescription")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("ReservationButtonText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReservationCallToActionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReservationCallToActionTitle")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("TheatreInformationId")
                        .HasColumnType("int");

                    b.Property<string>("TheatreName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("TheatreInformationId", "LanguageId")
                        .IsUnique();

                    b.ToTable("TheatreInformationTranslations");
                });

            modelBuilder.Entity("Theatre.Api.Models.AdminActivity", b =>
                {
                    b.HasOne("Theatre.Api.Models.AdminUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("Theatre.Api.Models.CreditTypeTranslation", b =>
                {
                    b.HasOne("Theatre.Api.Models.CreditType", "CreditType")
                        .WithMany("Translations")
                        .HasForeignKey("CreditTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Theatre.Api.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreditType");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Theatre.Api.Models.GalleryAlbum", b =>
                {
                    b.HasOne("Theatre.Api.Models.MediaAsset", "CoverMediaAsset")
                        .WithMany()
                        .HasForeignKey("CoverMediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Theatre.Api.Models.NewsArticle", "NewsArticle")
                        .WithMany("GalleryAlbums")
                        .HasForeignKey("NewsArticleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Theatre.Api.Models.PitfEdition", "PitfEdition")
                        .WithMany("GalleryAlbums")
                        .HasForeignKey("PitfEditionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Theatre.Api.Models.Show", "Show")
                        .WithMany("GalleryAlbums")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CoverMediaAsset");

                    b.Navigation("NewsArticle");

                    b.Navigation("PitfEdition");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Theatre.Api.Models.GalleryAlbumMedia", b =>
                {
                    b.HasOne("Theatre.Api.Models.GalleryAlbum", "GalleryAlbum")
                        .WithMany("GalleryAlbumMedia")
                        .HasForeignKey("GalleryAlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Theatre.Api.Models.MediaAsset", "MediaAsset")
                        .WithMany("GalleryAlbumMedia")
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GalleryAlbum");

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("Theatre.Api.Models.GalleryAlbumTranslation", b =>
                {
                    b.HasOne("Theatre.Api.Models.GalleryAlbum", "GalleryAlbum")
                        .WithMany("Translations")
                        .HasForeignKey("GalleryAlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Theatre.Api.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GalleryAlbum");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Theatre.Api.Models.LocationTranslation", b =>
                {
                    b.HasOne("Theatre.Api.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Theatre.Api.Models.Location", "Location")
                        .WithMany("Translations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Theatre.Api.Models.MediaAssetTranslation", b =>
                {
                    b.HasOne("Theatre.Api.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Theatre.Api.Models.MediaAsset", "MediaAsset")
                        .WithMany("Translations")
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("Theatre.Api.Models.NewsArticle", b =>
                {
                    b.HasOne("Theatre.Api.Models.MediaAsset", "CardThumbnailMediaAsset")
                        .WithMany()
                        .HasForeignKey("CardThumbnailMediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Theatre.Api.Models.MediaAsset", "CoverMediaAsset")
                        .WithMany()
                        .HasForeignKey("CoverMediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CardThumbnailMediaAsset");

                    b.Navigation("CoverMediaAsset");
                });

            modelBuilder.Entity("Theatre.Api.Models.NewsArticleTranslation", b =>
                {
                    b.HasOne("Theatre.Api.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Theatre.Api.Models.NewsArticle", "NewsArticle")
                        .WithMany("Translations")
                        .HasForeignKey("NewsArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("NewsArticle");
                });

            modelBuilder.Entity("Theatre.Api.Models.NewsExternalLink", b =>
                {
                    b.HasOne("Theatre.Api.Models.NewsArticle", "NewsArticle")
                        .WithMany("RelatedExternalLinks")
                        .HasForeignKey("NewsArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsArticle");
                });

            modelBuilder.Entity("Theatre.Api.Models.Person", b =>
                {
                    b.HasOne("Theatre.Api.Models.MediaAsset", "ProfileMediaAsset")
                        .WithMany()
                        .HasForeignKey("ProfileMediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProfileMediaAsset");
                });

            modelBuilder.Entity("Theatre.Api.Models.PersonTranslation", b =>
                {
                    b.HasOne("Theatre.Api.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Theatre.Api.Models.Person", "Person")
                        .WithMany("Translations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Theatre.Api.Models.PitfEdition", b =>
                {
                    b.HasOne("Theatre.Api.Models.MediaAsset", "CoverMediaAsset")
                        .WithMany()
                        .HasForeignKey("CoverMediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Theatre.Api.Models.MediaAsset", "LogoMediaAsset")
                        .WithMany()
                        .HasForeignKey("LogoMediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CoverMediaAsset");

                    b.Navigation("LogoMediaAsset");
                });

            modelBuilder.Entity("Theatre.Api.Models.PitfEditionTranslation", b =>
                {
                    b.HasOne("Theatre.Api.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Theatre.Api.Models.PitfEdition", "PitfEdition")
                        .WithMany("Translations")
                        .HasForeignKey("PitfEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("PitfEdition");
                });

            modelBuilder.Entity("Theatre.Api.Models.Show", b =>
                {
                    b.HasOne("Theatre.Api.Models.MediaAsset", "FeaturedMediaAsset")
                        .WithMany()
                        .HasForeignKey("FeaturedMediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Theatre.Api.Models.MediaAsset", "PosterMediaAsset")
                        .WithMany()
                        .HasForeignKey("PosterMediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Theatre.Api.Models.ShowCategory", "ShowCategory")
                        .WithMany("Shows")
                        .HasForeignKey("ShowCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FeaturedMediaAsset");

                    b.Navigation("PosterMediaAsset");

                    b.Navigation("ShowCategory");
                });

            modelBuilder.Entity("Theatre.Api.Models.ShowCategoryTranslation", b =>
                {
                    b.HasOne("Theatre.Api.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Theatre.Api.Models.ShowCategory", "ShowCategory")
                        .WithMany("Translations")
                        .HasForeignKey("ShowCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("ShowCategory");
                });

            modelBuilder.Entity("Theatre.Api.Models.ShowCredit", b =>
                {
                    b.HasOne("Theatre.Api.Models.CreditType", "CreditType")
                        .WithMany("ShowCredits")
                        .HasForeignKey("CreditTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Theatre.Api.Models.Person", "Person")
                        .WithMany("ShowCredits")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Theatre.Api.Models.Show", "Show")
                        .WithMany("Credits")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditType");

                    b.Navigation("Person");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Theatre.Api.Models.ShowPerformance", b =>
                {
                    b.HasOne("Theatre.Api.Models.Location", "Location")
                        .WithMany("Performances")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Theatre.Api.Models.Show", "Show")
                        .WithMany("Performances")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Theatre.Api.Models.ShowTranslation", b =>
                {
                    b.HasOne("Theatre.Api.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Theatre.Api.Models.Show", "Show")
                        .WithMany("Translations")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Theatre.Api.Models.StaticPage", b =>
                {
                    b.HasOne("Theatre.Api.Models.MediaAsset", "FeaturedMediaAsset")
                        .WithMany()
                        .HasForeignKey("FeaturedMediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Theatre.Api.Models.MediaAsset", "ParallaxMediaAsset")
                        .WithMany()
                        .HasForeignKey("ParallaxMediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Theatre.Api.Models.MediaAsset", "SocialSharingMediaAsset")
                        .WithMany()
                        .HasForeignKey("SocialSharingMediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FeaturedMediaAsset");

                    b.Navigation("ParallaxMediaAsset");

                    b.Navigation("SocialSharingMediaAsset");
                });

            modelBuilder.Entity("Theatre.Api.Models.StaticPageTranslation", b =>
                {
                    b.HasOne("Theatre.Api.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Theatre.Api.Models.StaticPage", "StaticPage")
                        .WithMany("Translations")
                        .HasForeignKey("StaticPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("StaticPage");
                });

            modelBuilder.Entity("Theatre.Api.Models.TheatreInformation", b =>
                {
                    b.HasOne("Theatre.Api.Models.MediaAsset", "AboutPreviewMediaAsset")
                        .WithMany()
                        .HasForeignKey("AboutPreviewMediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Theatre.Api.Models.MediaAsset", "FaviconMediaAsset")
                        .WithMany()
                        .HasForeignKey("FaviconMediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Theatre.Api.Models.MediaAsset", "HeroBackgroundMediaAsset")
                        .WithMany()
                        .HasForeignKey("HeroBackgroundMediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Theatre.Api.Models.MediaAsset", "LogoMediaAsset")
                        .WithMany()
                        .HasForeignKey("LogoMediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Theatre.Api.Models.MediaAsset", "PitfFeatureMediaAsset")
                        .WithMany()
                        .HasForeignKey("PitfFeatureMediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Theatre.Api.Models.MediaAsset", "PitfPageMediaAsset")
                        .WithMany()
                        .HasForeignKey("PitfPageMediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Theatre.Api.Models.MediaAsset", "ReservationBannerMediaAsset")
                        .WithMany()
                        .HasForeignKey("ReservationBannerMediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Theatre.Api.Models.MediaAsset", "SocialSharingMediaAsset")
                        .WithMany()
                        .HasForeignKey("SocialSharingMediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AboutPreviewMediaAsset");

                    b.Navigation("FaviconMediaAsset");

                    b.Navigation("HeroBackgroundMediaAsset");

                    b.Navigation("LogoMediaAsset");

                    b.Navigation("PitfFeatureMediaAsset");

                    b.Navigation("PitfPageMediaAsset");

                    b.Navigation("ReservationBannerMediaAsset");

                    b.Navigation("SocialSharingMediaAsset");
                });

            modelBuilder.Entity("Theatre.Api.Models.TheatreInformationTranslation", b =>
                {
                    b.HasOne("Theatre.Api.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Theatre.Api.Models.TheatreInformation", "TheatreInformation")
                        .WithMany("Translations")
                        .HasForeignKey("TheatreInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("TheatreInformation");
                });

            modelBuilder.Entity("Theatre.Api.Models.CreditType", b =>
                {
                    b.Navigation("ShowCredits");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Theatre.Api.Models.GalleryAlbum", b =>
                {
                    b.Navigation("GalleryAlbumMedia");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Theatre.Api.Models.Location", b =>
                {
                    b.Navigation("Performances");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Theatre.Api.Models.MediaAsset", b =>
                {
                    b.Navigation("GalleryAlbumMedia");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Theatre.Api.Models.NewsArticle", b =>
                {
                    b.Navigation("GalleryAlbums");

                    b.Navigation("RelatedExternalLinks");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Theatre.Api.Models.Person", b =>
                {
                    b.Navigation("ShowCredits");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Theatre.Api.Models.PitfEdition", b =>
                {
                    b.Navigation("GalleryAlbums");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Theatre.Api.Models.Show", b =>
                {
                    b.Navigation("Credits");

                    b.Navigation("GalleryAlbums");

                    b.Navigation("Performances");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Theatre.Api.Models.ShowCategory", b =>
                {
                    b.Navigation("Shows");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Theatre.Api.Models.StaticPage", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Theatre.Api.Models.TheatreInformation", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
