import { useEffect, useState } from 'react'
import { adminApi } from '../api'
import { LanguageTabs, LoadingSkeleton, PageHeader, Toast } from '../components/AdminUi'

export function WebsiteInformationPage() {
  const [form, setForm] = useState(null); const [saved, setSaved] = useState(null); const [lang, setLang] = useState('sq'); const [toast, setToast] = useState('')
  useEffect(() => { adminApi.website().then(data => { setForm(data); setSaved(JSON.stringify(data)) }) }, [])
  const dirty = form && JSON.stringify(form) !== saved
  useEffect(() => { const warn = e => { if (dirty) { e.preventDefault(); e.returnValue = '' } }; addEventListener('beforeunload', warn); return () => removeEventListener('beforeunload', warn) }, [dirty])
  if (!form) return <LoadingSkeleton />
  const translation = form.translations.find(x => x.languageCode === lang)
  const setField = (key, value) => setForm({ ...form, [key]: value })
  const setTranslation = (key, value) => setForm({ ...form, translations: form.translations.map(x => x.languageCode === lang ? { ...x, [key]: value } : x) })
  const save = async e => { e.preventDefault(); const data = await adminApi.saveWebsite(form); setForm(data); setSaved(JSON.stringify(data)); setToast('Website information saved.') }
  return <><PageHeader eyebrow="Website" title="Website Information" description="Manage public contact details, branding, social links and localized footer content." actions={<span className={dirty ? 'unsaved-chip' : 'saved-chip'}>{dirty ? 'Unsaved changes' : 'All changes saved'}</span>} /><form className="admin-form" onSubmit={save}>
    <section className="admin-panel"><h2>Contact details</h2><div className="form-grid"><label>Address *<input required value={form.address} onChange={e => setField('address', e.target.value)} /></label><label>Phone *<input required pattern="[+0-9() .-]{6,}" value={form.phone} onChange={e => setField('phone', e.target.value)} /></label><label>Email *<input required type="email" value={form.email} onChange={e => setField('email', e.target.value)} /></label><label>Ticket reservation URL<input type="url" value={form.reservationUrl ?? ''} onChange={e => setField('reservationUrl', e.target.value)} /></label><label>Facebook URL<input type="url" value={form.facebookUrl ?? ''} onChange={e => setField('facebookUrl', e.target.value)} /></label><label>Instagram URL<input type="url" value={form.instagramUrl ?? ''} onChange={e => setField('instagramUrl', e.target.value)} /></label></div></section>
    <section className="admin-panel"><h2>Localized information</h2><LanguageTabs active={lang} onChange={setLang} /><div className="form-grid"><label>Theatre name *<input required value={translation.theatreName} onChange={e => setTranslation('theatreName', e.target.value)} /></label><label>Public address *<input required value={translation.addressDisplayText} onChange={e => setTranslation('addressDisplayText', e.target.value)} /></label><label className="full">Footer copyright text<textarea rows="3" value={translation.footerCopyrightText} onChange={e => setTranslation('footerCopyrightText', e.target.value)} /></label></div></section>
    <section className="admin-panel"><h2>Brand media</h2><p className="admin-help">Media selection is ID-based until the Media Library picker is connected.</p><div className="form-grid"><label>Logo media ID<input type="number" value={form.logoMediaAssetId ?? ''} onChange={e => setField('logoMediaAssetId', e.target.value ? Number(e.target.value) : null)} /></label><label>Favicon media ID<input type="number" value={form.faviconMediaAssetId ?? ''} onChange={e => setField('faviconMediaAssetId', e.target.value ? Number(e.target.value) : null)} /></label><label>Social sharing image ID<input type="number" value={form.socialSharingMediaAssetId ?? ''} onChange={e => setField('socialSharingMediaAssetId', e.target.value ? Number(e.target.value) : null)} /></label></div></section>
    <div className="sticky-save"><button className="admin-primary-button" disabled={!dirty}>Save changes</button><a className="admin-outline-button" href={`#/${lang}`} target="_blank">Preview public page ↗</a></div></form><Toast message={toast} onClose={() => setToast('')} /></>
}
