import { createContext, useContext, useMemo, useState } from 'react'

const sq = {
  Overview: 'Përmbledhje', Dashboard: 'Paneli kryesor', 'Theatre operations': 'Menaxhimi i teatrit', Reservations: 'Rezervimet',
  'Our plays': 'Shfaqjet tona', 'Guest plays': 'Shfaqjet mysafire', Performances: 'Terminet', 'Seating templates': 'Skemat e ulëseve', Customers: 'Klientët',
  'Website content': 'Përmbajtja e faqes', Homepage: 'Ballina', News: 'Lajmet', Gallery: 'Galeria', Pages: 'Faqet', Communication: 'Komunikimi',
  'Contact Messages': 'Mesazhet e kontaktit', Subscribers: 'Abonuesit', Website: 'Faqja e internetit', 'Website Information': 'Të dhënat e faqes',
  'Navigation & Footer': 'Navigimi dhe fundi i faqes', Translations: 'Përkthimet', 'SEO & Links': 'SEO dhe lidhjet', 'Media Library': 'Biblioteka e mediave',
  Administration: 'Administrimi', 'Users & Roles': 'Përdoruesit dhe rolet', 'Activity Log': 'Regjistri i aktiviteteve',
  'Backups & System': 'Kopjet rezervë dhe sistemi', Settings: 'Cilësimet', 'Open website': 'Hap faqen',
  'Search the theatre archive…': 'Kërko në arkivin e teatrit…', 'Change password': 'Ndrysho fjalëkalimin',
  'Update your account security': 'Përditëso sigurinë e llogarisë', 'Log out': 'Dil', 'End this admin session': 'Përfundo këtë sesion',
  'Super Admin': 'Super Administrator', 'Content Editor': 'Redaktor i përmbajtjes', Cancel: 'Anulo', Confirm: 'Konfirmo', Save: 'Ruaj',
  'Please confirm': 'Ju lutemi konfirmoni', 'Admin action': 'Veprim administrativ', Active: 'Aktiv', Confirmed: 'Konfirmuar',
  Unconfirmed: 'Pakonfirmuar', Cancelled: 'Anuluar', Released: 'Liruar', Published: 'Publikuar', Scheduled: 'Planifikuar',
  Welcome: 'Mirë se erdhe', 'What is happening at the theatre, at a glance.': 'Çfarë po ndodh në teatër, me një vështrim.',
  'Bookings today': 'Rezervimet sot', 'Upcoming performances': 'Terminet e ardhshme', 'New messages': 'Mesazhe të reja',
  'Published plays': 'Shfaqje të publikuara', 'Draft plays': 'Shfaqje në draft', View: 'Shiko', Today: 'Sot', Yesterday: 'Dje',
  'New bookings today': 'Rezervimet e reja sot', 'Reservations received today and the performances they belong to.': 'Rezervimet e pranuara sot dhe terminet përkatëse.',
  Play: 'Shfaqja', seats: 'ulëse', seat: 'ulëse', 'No new bookings today': 'Sot nuk ka rezervime të reja',
  'New reservations will appear here together with their play and performance.': 'Rezervimet e reja do të shfaqen këtu bashkë me shfaqjen dhe terminin.',
  'Live booking overview': 'Pasqyra e rezervimeve aktive', 'Open reservations': 'Rezervimet e hapura',
  'Upcoming performances using the theatre seat map.': 'Terminet e ardhshme që përdorin skemën e ulëseve të teatrit.',
  'Manage reservations': 'Menaxho rezervimet', bookings: 'rezervime', Open: 'Hapur', Closed: 'Mbyllur',
  'No internal reservations are open': 'Nuk ka rezervime të brendshme të hapura',
  'Publish an upcoming performance with a seating template to see occupancy here.': 'Publiko një termin të ardhshëm me skemë ulësesh për ta parë zënien këtu.',
  'Set up a performance': 'Konfiguro një termin', Inbox: 'Kutia hyrëse', 'Contact messages': 'Mesazhet e kontaktit',
  'See all': 'Shiko të gjitha', 'No messages yet.': 'Ende nuk ka mesazhe.', Audience: 'Audienca', 'Latest subscribers': 'Abonuesit e fundit',
  Subscribed: 'Abonuar', 'No subscribers yet.': 'Ende nuk ka abonues.', Shortcuts: 'Shkurtoret', 'Quick actions': 'Veprime të shpejta',
  'Create play': 'Krijo shfaqje', 'Add performance': 'Shto termin', 'Read messages': 'Lexo mesazhet', 'Edit homepage': 'Ndrysho ballinën',
  Operations: 'Operacionet', 'Performance reservations': 'Rezervimet e terminit',
  'Manage customers, live seat availability, confirmations and reservation history.': 'Menaxho klientët, ulëset e lira, konfirmimet dhe historikun e rezervimeve.',
  'Now accepting reservations': 'Tani pranon rezervime', 'Open performances': 'Terminet e hapura', 'No internal performances are accepting reservations right now.': 'Aktualisht asnjë termin i brendshëm nuk pranon rezervime.',
  'Select a performance': 'Zgjidh një termin', 'Select an internal-reservation performance': 'Zgjidh një termin me rezervim të brendshëm',
  'No venue': 'Pa sallë', 'Venue to be announced': 'Salla do të njoftohet', 'Live seating': 'Gjendja e ulëseve',
  Available: 'E lirë', 'Public · unconfirmed': 'Publik · i pakonfirmuar', 'Admin reservation': 'Rezervim nga administrata',
  'Admin-blocked': 'Bllokuar nga administrata', Disabled: 'Joaktive', 'New reservation': 'Rezervim i ri', 'Block seats': 'Blloko ulëset',
  'Clear selection': 'Pastro përzgjedhjen', 'No selection': 'Asgjë e përzgjedhur',
  'Select a reservation row or occupied seat to view customer and reservation details.': 'Zgjidh një rezervim ose ulëse të zënë për t’i parë hollësitë.',
  'New customer': 'Klient i ri', 'Existing customer': 'Klient ekzistues', 'Find a customer': 'Gjej një klient',
  'Type at least 2 characters…': 'Shkruaj së paku 2 karaktere…', 'No matching customers found.': 'Nuk u gjet asnjë klient.',
  'Full name': 'Emri i plotë', 'Country prefix': 'Prefiksi i shtetit', Phone: 'Telefoni', 'Email (optional)': 'Email-i (opsional)',
  'Private note': 'Shënim privat', Optional: 'Opsionale', 'No seats selected': 'Nuk është zgjedhur asnjë ulëse',
  'Create customer & reservation': 'Krijo klientin dhe rezervimin', 'Create reservation': 'Krijo rezervimin', 'Cancel and close': 'Anulo dhe mbyll',
  'Seat management': 'Menaxhimi i ulëseve', Move: 'Zhvendos', Add: 'Shto', Remove: 'Hiq', Section: 'Sektori', Seats: 'Ulëset',
  Reserved: 'Rezervuar', Source: 'Burimi', 'Public website': 'Faqja publike', 'Admin-created': 'Krijuar nga administrata',
  'Private admin note': 'Shënim privat i administratorit', 'Save note': 'Ruaj shënimin', 'Review seats & confirm': 'Kontrollo ulëset dhe konfirmo',
  'Mark as unconfirmed': 'Shëno si të pakonfirmuar', 'Cancel reservation': 'Anulo rezervimin', 'Reactivate reservation': 'Riaktivizo rezervimin',
  'Permanent action': 'Veprim i përhershëm', 'Delete reservation': 'Fshije rezervimin', 'Reservation records': 'Të dhënat e rezervimeve',
  'Filter and export data': 'Filtro dhe eksporto të dhënat', 'Excel layout': 'Formati në Excel', 'One row per reservation': 'Një rresht për rezervim',
  'One row per seat': 'Një rresht për ulëse', 'Export all Excel': 'Eksporto të gjitha në Excel', 'Filtered Excel': 'Eksporto filtrimin në Excel',
  'Schema + reservations': 'Skema dhe rezervimet', 'Customer or phone': 'Klienti ose telefoni', Row: 'Rreshti',
  'Reservation date': 'Data e rezervimit', Confirmation: 'Konfirmimi', Status: 'Statusi', Sort: 'Renditja', All: 'Të gjitha',
  'Newest first': 'Më të rejat së pari', 'Oldest first': 'Më të vjetrat së pari', 'Clear all filters': 'Pastro të gjithë filtrat',
  'No reservations found': 'Nuk u gjet asnjë rezervim', 'There are no reservations matching the current filters.': 'Nuk ka rezervime që përputhen me filtrat aktualë.',
  Customer: 'Klienti', 'Reserved seats': 'Ulëset e rezervuara', 'Section / row': 'Sektori / rreshti', Comment: 'Komenti', Previous: 'E mëparshme', Next: 'Tjetra',
}

Object.assign(sq, {
  Content: 'Përmbajtja', Information: 'Informacioni', Actions: 'Veprimet', Action: 'Veprimi', Edit: 'Ndrysho', Delete: 'Fshije', Close: 'Mbyll',
  Archive: 'Arkivo', Archived: 'Arkivuar', Completed: 'Përfunduar', Featured: 'E veçuar', Error: 'Gabim', Errors: 'Gabimet',
  Language: 'Gjuha', Albanian: 'Shqip', English: 'Anglisht', 'Basic information': 'Informacioni bazë', 'Publication': 'Publikimi',
  'Publication state': 'Gjendja e publikimit', Category: 'Kategoria', Description: 'Përshkrimi', 'Description *': 'Përshkrimi *',
  Title: 'Titulli', 'Title *': 'Titulli *', Name: 'Emri', Email: 'Email-i', 'Email *': 'Email-i *', Address: 'Adresa', 'Address *': 'Adresa *',
  Date: 'Data', 'Date & time': 'Data dhe ora', Day: 'Dita', Month: 'Muaji', Year: 'Viti', Search: 'Kërko', Filters: 'Filtrat',
  'Clear filters': 'Pastro filtrat', 'Choose month': 'Zgjidh muajin', 'All statuses': 'Të gjitha statuset', 'All states': 'Të gjitha gjendjet',
  'All years': 'Të gjitha vitet', 'All venues': 'Të gjitha sallat', 'All plays': 'Të gjitha shfaqjet', 'All subscribers': 'Të gjithë abonuesit',
  'Create play': 'Krijo shfaqje', 'Back to plays': 'Kthehu te shfaqjet', 'Archive play': 'Arkivo shfaqjen', 'Guest play': 'Shfaqje mysafire',
  'Play type': 'Lloji i shfaqjes', 'Play type *': 'Lloji i shfaqjes *', 'Our production': 'Produksion i yni', 'Lifecycle status': 'Statusi i ciklit',
  'Premiere date': 'Data e premierës', 'Production year': 'Viti i produksionit', 'Duration (minutes)': 'Kohëzgjatja (minuta)',
  'Age recommendation': 'Mosha e rekomanduar', 'Original language': 'Gjuha origjinale', 'Feature this play on the website': 'Veçoje këtë shfaqje në faqe',
  Credits: 'Kreditet', Media: 'Media', 'Main poster': 'Posteri kryesor', 'Featured / hero image': 'Imazhi kryesor', Trailer: 'Traileri',
  'Gallery picture': 'Fotografi e galerisë', 'Choose existing': 'Zgjidh ekzistuese', 'Choose from Media Library': 'Zgjidh nga biblioteka e mediave',
  'Add or upload picture': 'Shto ose ngarko fotografi', 'Upload pictures': 'Ngarko fotografi', 'Drag to reorder': 'Tërhiq për ta rirenditur',
  'Manage performances': 'Menaxho terminet', 'Add performance': 'Shto termin', 'Invalid performance date': 'Data e terminit nuk është e vlefshme',
  Venue: 'Salla', Availability: 'Disponueshmëria', Calendar: 'Kalendari', 'Internal seating reservation': 'Rezervim i brendshëm me ulëse',
  'Create customer': 'Krijo klient', 'Edit customer': 'Ndrysho klientin', 'Delete customer': 'Fshije klientin', 'Customer profile': 'Profili i klientit',
  'First reservation': 'Rezervimi i parë', 'Last updated': 'Përditësimi i fundit', 'Internal notes': 'Shënime të brendshme',
  'Export CSV': 'Eksporto CSV', 'Export filtered': 'Eksporto të filtruarat', 'Export history': 'Eksporto historikun',
  'Add news article': 'Shto lajm', 'Back to news': 'Kthehu te lajmet', 'Article settings': 'Cilësimet e artikullit',
  'Article media': 'Media e artikullit', 'Featured article': 'Artikull i veçuar', 'External article': 'Artikull i jashtëm',
  'External source name *': 'Emri i burimit të jashtëm *', 'External video link': 'Lidhja e videos së jashtme',
  'Media Library': 'Biblioteka e mediave', 'File details': 'Hollësitë e skedarit', 'File name': 'Emri i skedarit', 'Copy file URL': 'Kopjo URL-në e skedarit',
  'Delete unused file': 'Fshije skedarin e papërdorur', 'Allowed uploads': 'Ngarkimet e lejuara', 'Failed uploads': 'Ngarkimet e dështuara',
  'Gallery picture': 'Fotografi e galerisë', 'Theatre gallery pictures': 'Fotografitë e galerisë së teatrit', 'Play gallery folders': 'Dosjet e galerive të shfaqjeve',
  'Open public gallery': 'Hap galerinë publike', Feature: 'Veço', 'Shown publicly': 'Shfaqet publikisht', 'Hidden publicly': 'Fshehur publikisht',
  'Contact details': 'Të dhënat e kontaktit', 'Contact and social media': 'Kontakti dhe rrjetet sociale', 'Contact phone': 'Telefoni i kontaktit',
  'Facebook URL': 'URL-ja e Facebook-ut', 'Instagram URL': 'URL-ja e Instagram-it', 'Google Maps embed URL': 'URL-ja e hartës Google',
  'Website information': 'Të dhënat e faqes', 'Brand media': 'Materialet e brendit', 'Header background': 'Sfondi i ballinës',
  'Footer logo': 'Logoja në fund të faqes', 'Footer wording': 'Teksti i fundit të faqes', 'Footer links': 'Lidhjet në fund të faqes',
  'Default website language': 'Gjuha e parazgjedhur e faqes', 'Supported languages': 'Gjuhët e mbështetura', 'Save language setting': 'Ruaj cilësimin e gjuhës',
  'Change Password': 'Ndrysho fjalëkalimin', 'Current password': 'Fjalëkalimi aktual', 'New password': 'Fjalëkalimi i ri',
  'Confirm new password': 'Konfirmo fjalëkalimin e ri', 'Enter your password': 'Shkruaj fjalëkalimin',
  Administrator: 'Administrator', Administrators: 'Administratorët', 'Active account': 'Llogari aktive', 'Users and roles': 'Përdoruesit dhe rolet',
  Database: 'Baza e të dhënave', Environment: 'Mjedisi', 'Application version': 'Versioni i aplikacionit',
  'Contact submission': 'Mesazh kontakti', 'Delete spam': 'Fshije si spam', Read: 'Lexuar', Unread: 'Palexuar', Spam: 'Spam',
  'Newsletter subscribers': 'Abonuesit e buletinit', Anonymized: 'Anonimizuar', 'Delete data': 'Fshiji të dhënat',
  'SEO recommendations': 'Rekomandimet SEO', Recommended: 'Rekomandohet', Missing: 'Mungon', 'Broken media references': 'Referenca të prishura të mediave',
  'Performance date & time': 'Data dhe ora e terminit', 'Reason or comment': 'Arsyeja ose komenti', 'Admin comment': 'Komenti i administratorit',
  'Save customer': 'Ruaj klientin', 'Delete permanently': 'Fshije përgjithmonë', 'Release blocked seat': 'Liro ulësen e bllokuar',
  'This seat is intentionally unavailable and has no customer reservation.': 'Kjo ulëse është bllokuar qëllimisht dhe nuk ka rezervim klienti.',
  'Blocked seats have no customer and appear unavailable publicly.': 'Ulëset e bllokuara nuk kanë klient dhe shfaqen si të zëna në faqen publike.',
  'Choose a play, venue and performance date to load its live seating and reservations.': 'Zgjidh shfaqjen, sallën dhe datën për t’i ngarkuar ulëset dhe rezervimet.',
  'Search by name, phone number, or email. Only the first 8 matches will be shown.': 'Kërko me emër, telefon ose email. Shfaqen vetëm 8 rezultatet e para.',
  'Enter a complete email address or leave the optional email field empty.': 'Shkruaj një email të plotë ose lëre fushën opsionale të zbrazët.',
  'Add a note about this reservation…': 'Shto një shënim për këtë rezervim…', 'Add information for the theatre team…': 'Shto informacion për ekipin e teatrit…',
  'Reservations could not be loaded': 'Rezervimet nuk mund të ngarkoheshin', 'Allow pop-ups to create the printable seating report.': 'Lejo dritaret pop-up për ta krijuar raportin për printim.',
  'No reservations match the selected filters.': 'Asnjë rezervim nuk përputhet me filtrat e zgjedhur.',
  'Reservation permanently deleted.': 'Rezervimi u fshi përgjithmonë.', 'Permanently delete reservation?': 'Ta fshijmë rezervimin përgjithmonë?',
  'The seats will immediately become available publicly. Reservation history will be retained.': 'Ulëset do të lirohen menjëherë në faqen publike. Historiku i rezervimit do të ruhet.',
  'Release blocked seat?': 'Ta lirojmë ulësen e bllokuar?', 'Release seat': 'Liro ulësen', 'Preparing seating report…': 'Duke përgatitur raportin e ulëseve…',
  'Customer A–Z': 'Klientët A–Z', 'Customer Z–A': 'Klientët Z–A', Result: 'Rezultati', Results: 'Rezultatet',
  'Shows / Plays': 'Shfaqjet', 'Create play': 'Krijo shfaqje', 'Edit play': 'Ndrysho shfaqjen',
  'Manage bilingual content, production information, media and publication state.': 'Menaxho përmbajtjen dygjuhëshe, produksionin, mediat dhe publikimin.',
  'Albanian content': 'Përmbajtja shqip', 'English content': 'Përmbajtja anglisht', Upcoming: 'E ardhshme', 'Sold out': 'E shitur',
  'Choose whether this is produced by AAB Theatre or hosted as a guest performance.': 'Zgjidh nëse shfaqja është produksion i Teatrit AAB apo shfaqje mysafire.',
  'Short description *': 'Përshkrimi i shkurtër *', 'Synopsis *': 'Përmbledhja *', 'Play media': 'Mediat e shfaqjes',
  'The poster is the main public image. Add a trailer and review gallery images already attached to this play.': 'Posteri është imazhi kryesor publik. Shto trailerin dhe kontrollo fotografitë e galerisë.',
  'No poster available': 'Nuk ka poster', 'Local video': 'Video lokale', 'External video link': 'Lidhje e jashtme e videos',
  'Trailer from Media Library': 'Trailer nga biblioteka e mediave', 'Trailer URL': 'URL-ja e trailerit', 'Open external trailer': 'Hap trailerin e jashtëm',
  items: 'elemente', 'Uploading…': 'Duke ngarkuar…', '+ Upload images': '+ Ngarko fotografi', '+ Upload more': '+ Ngarko të tjera',
  'No gallery attached': 'Nuk ka galeri', 'Ready to publish?': 'Gati për publikim?', Ready: 'Gati', Required: 'E detyrueshme',
  'New article': 'Artikull i ri', 'Create a bilingual news article for the public website.': 'Krijo një artikull dygjuhësh për faqen publike.',
  'Edit bilingual article content, publication settings and source information.': 'Ndrysho përmbajtjen dygjuhëshe, publikimin dhe të dhënat e burimit.',
  'Article unavailable': 'Artikulli nuk është i disponueshëm', 'Return to editor': 'Kthehu te redaktori', 'Preview article': 'Shiko paraprakisht artikullin',
  'Summary *': 'Përmbledhja *', 'Article content': 'Përmbajtja e artikullit', '(optional for video-led news)': '(opsionale për lajme me video)',
  'Upload images or MP4 videos. The main media is used on News cards and at the top of the article.': 'Ngarko fotografi ose video MP4. Media kryesore përdoret në kartelën e lajmit dhe në krye të artikullit.',
  '+ Upload media': '+ Ngarko media', 'Choose image or video from Media Library': 'Zgjidh fotografi ose video nga biblioteka e mediave',
  'Main media': 'Media kryesore', 'Remove main media': 'Hiq median kryesore', 'Use as main media': 'Përdore si media kryesore',
  'No article media': 'Nuk ka media të artikullit', 'Upload an image or video. The first file automatically becomes the main media.': 'Ngarko një fotografi ose video. Skedari i parë bëhet automatikisht media kryesore.',
  'News card thumbnail': 'Fotografia e kartelës së lajmit', 'Optional card image': 'Fotografi opsionale e kartelës', 'Online thumbnail': 'Fotografi nga interneti',
  'Online image URL': 'URL-ja e fotografisë', 'Online thumbnail preview': 'Pamja paraprake e fotografisë',
  'Related external coverage': 'Raportime të jashtme të ndërlidhura', 'Optional articles from other publishers covering the same topic. Links open in a new tab.': 'Artikuj opsionalë nga botues të tjerë për të njëjtën temë. Lidhjet hapen në skedë të re.',
  '+ Add related link': '+ Shto lidhje', 'Link title *': 'Titulli i lidhjes *', 'Source name': 'Emri i burimit', 'Publication date': 'Data e publikimit',
  'No related coverage': 'Nuk ka raportime të ndërlidhura', 'Add links only when another publisher has covered this story.': 'Shto lidhje vetëm kur një botues tjetër e ka mbuluar këtë lajm.',
  'Article ownership': 'Pronësia e artikullit', 'Our article': 'Artikulli ynë', 'Original article URL *': 'URL-ja e artikullit origjinal *',
  'Published on website': 'Publikuar në faqe', 'Create article': 'Krijo artikull', 'Save article': 'Ruaj artikullin', 'Saving…': 'Duke ruajtur…',
  'Unsaved changes': 'Ndryshime të paruajtura', 'All changes saved': 'Të gjitha ndryshimet u ruajtën', 'Choose or upload': 'Zgjidh ose ngarko',
  Select: 'Zgjidh', image: 'fotografi', video: 'video', 'image or video': 'fotografi ose video', Showing: 'Duke shfaqur', of: 'nga', 'Load more media': 'Ngarko më shumë media',
  'Nothing here yet': 'Ende nuk ka asgjë', 'No records found.': 'Nuk u gjet asnjë e dhënë.', 'Dismiss notification': 'Mbyll njoftimin',
  'These credits will be saved together with the new play.': 'Këto kredite do të ruhen bashkë me shfaqjen e re.',
  'Add pictures after the trailer by uploading files or choosing existing images.': 'Shto fotografi pas trailerit duke ngarkuar skedarë ose duke zgjedhur fotografi ekzistuese.',
  'Add the first gallery images using either option above.': 'Shto fotografitë e para të galerisë me njërën nga mundësitë më sipër.',
  'Choose from Media Library': 'Zgjidh nga biblioteka e mediave', 'Save changes': 'Ruaj ndryshimet', Preview: 'Shiko paraprakisht',
  'This media is displayed on the News card and article cover.': 'Kjo media shfaqet në kartelën dhe kopertinën e lajmit.',
  'Drag media to arrange the article gallery. Choose “Use as main media” to replace the cover above.': 'Tërhiq mediat për ta rregulluar galerinë. Zgjidh “Përdore si media kryesore” për ta zëvendësuar kopertinën.',
  Drag: 'Tërhiq',
  Theatre: 'Teatri', New: 'I ri', Resolved: 'Zgjidhur', 'Dashboard data could not be loaded.': 'Të dhënat e panelit nuk mund të ngarkoheshin.',
  'A read-only audit trail of actions by every administrator, including deleted accounts.': 'Regjistër vetëm për lexim i veprimeve të çdo administratori, duke përfshirë llogaritë e fshira.',
  'Search activity…': 'Kërko aktivitetin…', 'All administrators': 'Të gjithë administratorët', 'All actions': 'Të gjitha veprimet',
  'All content types': 'Të gjitha llojet e përmbajtjes', Details: 'Hollësitë', actions: 'veprime', Page: 'Faqja',
  Updated: 'Përditësuar', Created: 'Krijuar', Published: 'Publikuar', 'Auto-completed': 'Përfunduar automatikisht',
  'Deleted or removed': 'Fshirë ose hequr', 'Updated credits': 'Kreditet u përditësuan', System: 'Sistemi', Performance: 'Termini',
  'Media file': 'Skedar media', 'General Gallery': 'Galeria e përgjithshme', 'News article': 'Artikull lajmi', 'Static page': 'Faqe statike',
  'Backups & System': 'Kopjet rezervë dhe sistemi', 'Read-only operational status. This screen never runs a backup or restore.': 'Gjendje operative vetëm për lexim. Kjo faqe nuk nis kopje rezervë ose rikthim.',
  Connected: 'Lidhur', Development: 'Zhvillim', 'stored files': 'skedarë të ruajtur', 'How backups work': 'Si funksionojnë kopjet rezervë',
  'Backups are managed externally; no provider has reported status to this application.': 'Kopjet rezervë menaxhohen nga jashtë; asnjë ofrues nuk ka raportuar gjendje në këtë aplikacion.',
  'The database contains website text and records. Media storage contains uploaded images, documents and videos. A complete recovery requires both. Because no backup provider is connected to this application, dates remain “not reported” rather than pretending a backup exists.': 'Baza e të dhënave përmban tekstet dhe të dhënat e faqes. Hapësira e mediave përmban fotografi, dokumente dhe video. Rikthimi i plotë i kërkon të dyja. Meqë nuk është lidhur asnjë ofrues, datat shfaqen si “të paraportuara”.',
  'Last database backup': 'Kopja e fundit e bazës së të dhënave', 'Last media backup': 'Kopja e fundit e mediave',
  'Not reported by an external backup provider': 'Nuk është raportuar nga një ofrues i jashtëm', recorded: 'të regjistruara',
  'Recent application errors': 'Gabimet e fundit të aplikacionit', 'Open Media Library': 'Hap bibliotekën e mediave',
  'Missing file': 'Skedari që mungon', 'Expected location': 'Vendndodhja e pritur', Time: 'Koha', Type: 'Lloji', 'What happened': 'Çfarë ndodhi', Request: 'Kërkesa', 'Reference ID': 'ID-ja e referencës',
  'Only active Media Library records are checked here. Deleted media is ignored. A listed record still exists as active, but its physical file is missing from upload storage.': 'Këtu kontrollohen vetëm mediat aktive. Mediat e fshira anashkalohen. Një e dhënë e listuar ekziston ende, por skedari fizik mungon.',
  'Use the reference ID to match an error with server logs. Technical exception details are never exposed here.': 'Përdor ID-në e referencës për ta lidhur gabimin me regjistrat e serverit. Hollësitë teknike nuk shfaqen këtu.',
  'No active media records point to missing files.': 'Asnjë media aktive nuk i referohet një skedari që mungon.', 'No recent server errors have been recorded.': 'Nuk është regjistruar asnjë gabim i fundit i serverit.',
  'Application-wide configuration, with editable controls only where they have a real effect.': 'Konfigurimi i aplikacionit, me fusha të ndryshueshme vetëm aty ku kanë efekt real.',
  'Missing translations block publication': 'Përkthimet që mungojnë e bllokojnë publikimin',
  'Supported languages and publication validation are part of the application’s data model and cannot safely be changed from a checkbox yet.': 'Gjuhët e mbështetura dhe kontrolli i publikimit janë pjesë e modelit të të dhënave dhe ende nuk mund të ndryshohen sigurt nga kjo fushë.',
  'Uploads and display': 'Ngarkimet dhe paraqitja', 'Maximum upload size': 'Madhësia maksimale e ngarkimit', 'Time format': 'Formati i orës', 'Locale based': 'Sipas gjuhës',
  'These values are enforced by server configuration or the interface. Making them editable here without changing those systems would create fake settings.': 'Këto vlera përcaktohen nga serveri ose ndërfaqja. Ndryshimi i tyre vetëm këtu do të krijonte cilësime pa efekt.',
  'Settings managed elsewhere': 'Cilësimet që menaxhohen diku tjetër', 'Subscriber export access': 'Qasja në eksportin e abonuesve',
  'Missing translations and content quality': 'Përkthimet që mungojnë dhe cilësia e përmbajtjes', 'Edit it in Website Information': 'Ndryshoje te Të dhënat e faqes',
  'Control it through administrator roles': 'Menaxhoje përmes roleve të administratorëve', 'Review SEO & Content Issues': 'Kontrollo SEO-n dhe problemet e përmbajtjes',
  'Default language saved.': 'Gjuha e parazgjedhur u ruajt.', 'Settings could not be saved.': 'Cilësimet nuk mund të ruheshin.',
  'Website health': 'Gjendja e faqes', 'SEO titles, descriptions and page addresses are generated automatically. Review only the issues below that need your input, such as missing translations, images or broken links.': 'Titujt SEO, përshkrimet dhe adresat gjenerohen automatikisht. Kontrollo vetëm problemet më poshtë që kërkojnë ndërhyrjen tënde, si përkthimet, imazhet ose lidhjet që mungojnë.',
  'Apply recommended fixes': 'Zbato rregullimet e rekomanduara', 'Checking…': 'Duke kontrolluar…', Warnings: 'Paralajmërime', Warning: 'Paralajmërim',
  'Search issues…': 'Kërko problemet…', 'All levels': 'Të gjitha nivelet', Level: 'Niveli', Issue: 'Problemi', 'Affected item': 'Elementi i prekur', 'What to do': 'Çfarë duhet bërë',
  'Open and fix': 'Hap dhe rregullo', 'Social image': 'Imazhi për rrjete sociale', 'No cover image or video is selected.': 'Nuk është zgjedhur imazh ose video kryesore.',
  'No matching content issues. Everything checked here looks complete.': 'Nuk ka probleme që përputhen. Gjithçka e kontrolluar duket e plotë.',
  Account: 'Llogaria', 'Use a unique password with at least 12 characters.': 'Përdor një fjalëkalim unik me të paktën 12 karaktere.',
  'The new passwords do not match.': 'Fjalëkalimet e reja nuk përputhen.', 'The password could not be changed.': 'Fjalëkalimi nuk mund të ndryshohej.', Changing: 'Duke ndryshuar',
  'Review missing and partially translated public content before publication.': 'Kontrollo përmbajtjen publike që mungon ose është përkthyer pjesërisht para publikimit.',
  'Language to review': 'Gjuha për kontroll', State: 'Gjendja', 'Last changed': 'Ndryshimi i fundit', 'Albanian to review': 'Shqip për kontroll', 'English to review': 'Anglisht për kontroll',
  'Total issues': 'Probleme gjithsej', 'Translation issues': 'Problemet e përkthimit', Shows: 'Shfaqjet', 'Homepage & website': 'Ballina dhe faqja',
  'Missing means that no usable translation has been entered. Partial means that only part of the required translated content exists.': 'Mungon do të thotë se nuk është dhënë përkthim i përdorshëm. Pjesërisht do të thotë se ekziston vetëm një pjesë e përmbajtjes së kërkuar.',
  'All checked translations are complete.': 'Të gjitha përkthimet e kontrolluara janë të plota.',
  'Newsletter Subscribers': 'Abonuesit e buletinit', 'Manage consented newsletter contacts and export the active mailing list.': 'Menaxho kontaktet që kanë dhënë pëlqimin dhe eksporto listën aktive të buletinit.',
  'Search email address…': 'Kërko adresën e emailit…', Unsubscribed: 'Çabonuar', records: 'të dhëna', Unknown: 'E panjohur',
  'Contact Messages': 'Mesazhet e kontaktit', 'Review contact submissions, update their state and reply through Gmail.': 'Shqyrto mesazhet e kontaktit, përditëso gjendjen dhe përgjigju përmes Gmail-it.',
  'Matching messages': 'Mesazhe që përputhen', 'Search sender, email or subject…': 'Kërko dërguesin, emailin ose subjektin…', Sender: 'Dërguesi', Subject: 'Subjekti', Submitted: 'Dërguar', Read: 'Lexuar', Archived: 'Arkivuar', Spam: 'Mesazh i padëshiruar',
  'Reply in Gmail': 'Përgjigju në Gmail', 'Save message': 'Ruaj mesazhin', 'Message updated.': 'Mesazhi u përditësua.',
  'Production credits': 'Kreditet e produksionit', 'Keep cast and crew structured, translated and in the order shown publicly.': 'Mbaji aktorët dhe ekipin të strukturuar, të përkthyer dhe sipas renditjes publike.',
  'Add credit': 'Shto kredit', 'No credits yet': 'Ende nuk ka kredite', 'Add the director, playwright, cast and production crew.': 'Shto regjisorin, dramaturgun, aktorët dhe ekipin e produksionit.',
  Person: 'Personi', 'Credit type': 'Lloji i kreditit', 'Role in Albanian': 'Roli në shqip', 'Role in English': 'Roli në anglisht', 'Character or additional detail': 'Personazhi ose hollësi shtesë', 'Save credits': 'Ruaj kreditet',
  'Article formatting': 'Formatimi i artikullit', Link: 'Lidhja', Quote: 'Citim', Undo: 'Zhbëj', Redo: 'Ribëj', 'Clear formatting': 'Pastro formatimin',
  Administrator: 'Administratori', Role: 'Roli', 'Last login': 'Hyrja e fundit', Never: 'Asnjëherë', Inactive: 'Joaktiv',
  'Users & Roles': 'Përdoruesit dhe rolet', 'Create administrators, assign roles, reset passwords and control access.': 'Krijo administratorë, cakto role, rivendos fjalëkalime dhe kontrollo qasjen.',
  'Edit administrator': 'Ndrysho administratorin', 'Create administrator': 'Krijo administrator', 'Save administrator': 'Ruaj administratorin', 'Full name': 'Emri i plotë', Password: 'Fjalëkalimi',
  'Content Editor': 'Redaktor i përmbajtjes', 'Super Admin': 'Super Administrator', 'Active account': 'Llogari aktive', 'Reset password': 'Rivendos fjalëkalimin', 'Remove access': 'Hiq qasjen', 'Delete permanently': 'Fshije përgjithmonë',
  'Current password': 'Fjalëkalimi aktual', 'New password': 'Fjalëkalimi i ri', 'Confirm new password': 'Konfirmo fjalëkalimin e ri',
  'Change Password': 'Ndrysho fjalëkalimin', 'You will be signed out after it changes.': 'Pas ndryshimit do të çkyçesh.',
  'Activity Log': 'Regjistri i aktiviteteve', 'Broken media references': 'Referencat e prishura të mediave', Environment: 'Mjedisi', 'Application version': 'Versioni i aplikacionit', 'Failed uploads': 'Ngarkimet e dështuara',
  Language: 'Gjuha', 'Default website language': 'Gjuha e parazgjedhur e faqes', 'Supported languages': 'Gjuhët e mbështetura', 'Save language setting': 'Ruaj cilësimin e gjuhës', 'Default pagination size': 'Numri i parazgjedhur për faqe', 'Allowed uploads': 'Ngarkimet e lejuara', 'Date format': 'Formati i datës',
  Error: 'Gabim', Errors: 'Gabime', Information: 'Informacion',
})

const Context = createContext(null)
export function AdminLanguageProvider({ children }) {
  const [language, setState] = useState(() => localStorage.getItem('admin-ui-language') === 'sq' ? 'sq' : 'en')
  const setLanguage = value => { const next = value === 'sq' ? 'sq' : 'en'; localStorage.setItem('admin-ui-language', next); setState(next) }
  const value = useMemo(() => ({ language, setLanguage, t: text => language === 'sq' ? (sq[text] ?? text) : text }), [language])
  return <Context.Provider value={value}>{children}</Context.Provider>
}
export function useAdminLanguage() { const value = useContext(Context); if (!value) throw new Error('AdminLanguageProvider is missing.'); return value }
