import { apiClient } from '../api/client'

export const adminApi = {
  session: () => apiClient.get('/api/admin/auth/session').then((r) => r.data),
  login: (data) => apiClient.post('/api/admin/auth/login', data).then((r) => r.data),
  logout: () => apiClient.post('/api/admin/auth/logout'),
  changePassword: (data) => apiClient.post('/api/admin/auth/change-password', data),
  dashboard: () => apiClient.get('/api/admin/dashboard').then((r) => r.data),
  website: () => apiClient.get('/api/admin/content/website-information').then((r) => r.data),
  saveWebsite: (data) => apiClient.put('/api/admin/content/website-information', data).then((r) => r.data),
  homepage: () => apiClient.get('/api/admin/content/homepage').then((r) => r.data),
  saveHomepage: (data) => apiClient.put('/api/admin/content/homepage', data).then((r) => r.data),
  translations: (params) => apiClient.get('/api/admin/content/translations', { params }).then((r) => r.data),
  shows: (params) => apiClient.get('/api/admin/shows', { params }).then((r) => r.data),
  show: (id) => apiClient.get(`/api/admin/shows/${id}`).then((r) => r.data),
  createShow: (data) => apiClient.post('/api/admin/shows', data).then((r) => r.data),
  saveShow: (id, data) => apiClient.put(`/api/admin/shows/${id}`, data).then((r) => r.data),
  showAction: (id, action) => apiClient.post(`/api/admin/shows/${id}/${action}`).then((r) => r.data),
  deleteShow: (id, confirmHistorical = false) => apiClient.delete(`/api/admin/shows/${id}`, { params: { confirmHistorical } }),
  showCredits: (id) => apiClient.get(`/api/admin/shows/${id}/credits`).then((r) => r.data),
  saveShowCredits: (id, credits) => apiClient.put(`/api/admin/shows/${id}/credits`, { credits }).then((r) => r.data),
  performances: (params) => apiClient.get('/api/admin/performances', { params }).then((r) => r.data),
  performance: (id) => apiClient.get(`/api/admin/performances/${id}`).then((r) => r.data),
  createPerformance: (data) => apiClient.post('/api/admin/performances', data).then((r) => r.data),
  savePerformance: (id, data) => apiClient.put(`/api/admin/performances/${id}`, data).then((r) => r.data),
  duplicatePerformance: (id) => apiClient.post(`/api/admin/performances/${id}/duplicate`).then((r) => r.data),
  deletePerformance: (id) => apiClient.delete(`/api/admin/performances/${id}`),
  media: (params) => apiClient.get('/api/admin/media', { params }).then((r) => r.data),
  uploadMedia: (file, onUploadProgress) => { const data = new FormData(); data.append('file', file); return apiClient.post('/api/admin/media', data, { onUploadProgress }).then((r) => r.data) },
  saveMedia: (id, data) => apiClient.put(`/api/admin/media/${id}`, data),
  deleteMedia: (id) => apiClient.delete(`/api/admin/media/${id}`),
  messages: (params) => apiClient.get('/api/admin/messages', { params }).then((r) => r.data),
  saveMessage: (id, data) => apiClient.put(`/api/admin/messages/${id}`, data).then((r) => r.data),
  deleteMessage: (id) => apiClient.delete(`/api/admin/messages/${id}`),
  subscribers: (params) => apiClient.get('/api/admin/subscribers', { params }).then((r) => r.data),
  exportSubscribers: () => apiClient.get('/api/admin/subscribers/export', { responseType: 'blob' }).then((r) => r.data),
  deleteSubscriber: (id) => apiClient.delete(`/api/admin/subscribers/${id}`),
  existingContent: (type, params) => apiClient.get(`/api/admin/existing-content/${type}`, { params }).then((r) => r.data),
  newsArticle: (id) => apiClient.get(`/api/admin/news/${id}`).then((r) => r.data),
  saveNewsArticle: (id, data) => apiClient.put(`/api/admin/news/${id}`, data).then((r) => r.data),
}
