import { apiClient } from '../api/client'

export const adminApi = {
  session: () => apiClient.get('/api/admin/auth/session').then((r) => r.data),
  login: (data) => apiClient.post('/api/admin/auth/login', data).then((r) => r.data),
  logout: () => apiClient.post('/api/admin/auth/logout'),
  changePassword: (data) => apiClient.post('/api/admin/auth/change-password', data),
  dashboard: () => apiClient.get('/api/admin/dashboard').then((r) => r.data),
  website: () => apiClient.get('/api/admin/content/website-information').then((r) => r.data),
  saveWebsite: (data) => apiClient.put('/api/admin/content/website-information', data).then((r) => r.data),
  navigation: () => apiClient.get('/api/admin/navigation').then((r) => r.data),
  saveNavigation: (data) => apiClient.put('/api/admin/navigation', data).then((r) => r.data),
  homepage: () => apiClient.get('/api/admin/content/homepage').then((r) => r.data),
  saveHomepage: (data) => apiClient.put('/api/admin/content/homepage', data).then((r) => r.data),
  translations: (params) => apiClient.get('/api/admin/content/translations', { params }).then((r) => r.data),
  pitf: () => apiClient.get('/api/admin/pitf').then((r) => r.data),
  savePitfPage: (data) => apiClient.put('/api/admin/pitf', data).then((r) => r.data),
  createPitfEdition: (data) => apiClient.post('/api/admin/pitf/editions', data).then((r) => r.data),
  savePitfEdition: (id, data) => apiClient.put(`/api/admin/pitf/editions/${id}`, data).then((r) => r.data),
  deletePitfEdition: (id) => apiClient.delete(`/api/admin/pitf/editions/${id}`),
  galleryAlbums: (params) => apiClient.get('/api/admin/gallery', { params: { ...params, cacheBust: Date.now() }, headers: { 'Cache-Control': 'no-cache' } }).then((r) => r.data),
  showGalleryFolders: () => apiClient.get('/api/admin/gallery/show-folders', { params: { cacheBust: Date.now() } }).then((r) => r.data),
  generalGallery: () => apiClient.get('/api/admin/gallery/general').then((r) => r.data),
  addGeneralGalleryMedia: (mediaAssetId) => apiClient.post('/api/admin/gallery/general/media', { mediaAssetId }),
  removeGeneralGalleryMedia: (mediaAssetId) => apiClient.delete(`/api/admin/gallery/general/media/${mediaAssetId}`),
  reorderGeneralGalleryMedia: (mediaAssetIds) => apiClient.put('/api/admin/gallery/general/order', { mediaAssetIds }),
  featureGeneralGalleryMedia: (mediaAssetId, isFeatured) => apiClient.put(`/api/admin/gallery/general/media/${mediaAssetId}/featured`, { isFeatured }),
  setGalleryAlbumVisibility: (albumId, isVisible) => apiClient.put(`/api/admin/gallery/albums/${albumId}/visibility`, { isVisible }),
  reorderGalleryAlbums: (albumIds) => apiClient.put('/api/admin/gallery/albums/order', { albumIds }),
  shows: (params) => apiClient.get('/api/admin/shows', { params }).then((r) => r.data),
  show: (id) => apiClient.get(`/api/admin/shows/${id}`).then((r) => r.data),
  createShow: (data) => apiClient.post('/api/admin/shows', data).then((r) => r.data),
  saveShow: (id, data) => apiClient.put(`/api/admin/shows/${id}`, data).then((r) => r.data),
  showAction: (id, action) => apiClient.post(`/api/admin/shows/${id}/${action}`).then((r) => r.data),
  deleteShow: (id, confirmHistorical = false) => apiClient.delete(`/api/admin/shows/${id}`, { params: { confirmHistorical } }),
  showCredits: (id) => apiClient.get(`/api/admin/shows/${id}/credits`).then((r) => r.data),
  showCreditTypes: () => apiClient.get('/api/admin/shows/credit-types').then((r) => r.data),
  saveShowCredits: (id, credits) => apiClient.put(`/api/admin/shows/${id}/credits`, { credits }).then((r) => r.data),
  attachShowGalleryMedia: (id, mediaAssetId) => apiClient.post(`/api/admin/shows/${id}/gallery`, { mediaAssetId }).then((r) => r.data),
  detachShowGalleryMedia: (id, mediaAssetId) => apiClient.delete(`/api/admin/shows/${id}/gallery/${mediaAssetId}`),
  manageLocalShowGallery: (id) => apiClient.post(`/api/admin/shows/${id}/gallery/manage-local`).then((r) => r.data),
  performances: (params) => apiClient.get('/api/admin/performances', { params }).then((r) => r.data),
  performance: (id) => apiClient.get(`/api/admin/performances/${id}`).then((r) => r.data),
  performanceConflicts: (params) => apiClient.get('/api/admin/performances/conflicts', { params }).then((r) => r.data),
  createPerformance: (data) => apiClient.post('/api/admin/performances', data).then((r) => r.data),
  createVenue: (data) => apiClient.post('/api/admin/performances/venues', data).then((r) => r.data),
  venues: () => apiClient.get('/api/admin/performances/venues').then((r) => r.data),
  saveVenue: (id, data) => apiClient.put(`/api/admin/performances/venues/${id}`, data).then((r) => r.data),
  deleteVenue: (id) => apiClient.delete(`/api/admin/performances/venues/${id}`),
  savePerformance: (id, data) => apiClient.put(`/api/admin/performances/${id}`, data).then((r) => r.data),
  duplicatePerformance: (id) => apiClient.post(`/api/admin/performances/${id}/duplicate`).then((r) => r.data),
  deletePerformance: (id) => apiClient.delete(`/api/admin/performances/${id}`),
  seatingTemplates: () => apiClient.get('/api/admin/seating-templates').then((r) => r.data),
  saveSeatingTemplate: (id, data) => apiClient.put(`/api/admin/seating-templates/${id}`, data).then(r => r.data),
  resetSeatingTemplate: id => apiClient.post(`/api/admin/seating-templates/${id}/reset`).then(r => r.data),
  performanceLayout: id => apiClient.get(`/api/admin/reservations/performances/${id}/layout`).then(r => r.data),
  savePerformanceLayout: (id, data) => apiClient.put(`/api/admin/reservations/performances/${id}/layout`, data).then(r => r.data),
  reservations: params => apiClient.get('/api/admin/reservations', { params }).then(r => r.data),
  reservation: id => apiClient.get(`/api/admin/reservations/${id}`).then(r => r.data),
  reservationSeats: performanceId => apiClient.get(`/api/admin/reservations/performances/${performanceId}/seats`).then(r => r.data),
  createReservation: data => apiClient.post('/api/admin/reservations', data).then(r => r.data),
  updateReservation: (id, data) => apiClient.patch(`/api/admin/reservations/${id}`, data),
  deleteReservation: id => apiClient.delete(`/api/admin/reservations/${id}`),
  blockSeats: (performanceId, data) => apiClient.post(`/api/admin/reservations/performances/${performanceId}/blocks`, data),
  releaseBlock: allocationId => apiClient.delete(`/api/admin/reservations/blocks/${allocationId}`),
  customers: params => apiClient.get('/api/admin/reservations/customers', { params }).then(r => r.data),
  customer: id => apiClient.get(`/api/admin/reservations/customers/${id}`).then(r => r.data),
  updateCustomer: (id, data) => apiClient.put(`/api/admin/reservations/customers/${id}`, data),
  deleteCustomer: id => apiClient.delete(`/api/admin/reservations/customers/${id}`),
  anonymizeCustomer: id => apiClient.post(`/api/admin/reservations/customers/${id}/anonymize`),
  customerAudit: id => apiClient.get(`/api/admin/reservations/${id}/audit`).then(r => r.data),
  exportCustomers: params => apiClient.get('/api/admin/reservations/customers/export', { params, responseType: 'blob' }).then(r => r.data),
  exportReservations: params => apiClient.get('/api/admin/reservations/export', { params, responseType: 'blob' }).then(r => r.data),
  media: (params) => apiClient.get('/api/admin/media', { params }).then((r) => r.data),
  mediaItem: (id) => apiClient.get(`/api/admin/media/${id}`).then((r) => r.data),
  mediaUsage: (id) => apiClient.get(`/api/admin/media/${id}/usage`).then((r) => r.data),
  uploadMedia: (file, onUploadProgress) => { const data = new FormData(); data.append('file', file); return apiClient.post('/api/admin/media', data, { onUploadProgress }).then((r) => r.data) },
  saveMedia: (id, data) => apiClient.put(`/api/admin/media/${id}`, data),
  replaceMedia: (id, file) => { const data = new FormData(); data.append('file', file); return apiClient.put(`/api/admin/media/${id}/file`, data).then((r) => r.data) },
  deleteMedia: (id) => apiClient.delete(`/api/admin/media/${id}`),
  staticPages: () => apiClient.get('/api/admin/pages').then(r => r.data),
  saveStaticPage: (id, data) => apiClient.put(`/api/admin/pages/${id}`, data).then(r => r.data),
  messages: (params) => apiClient.get('/api/admin/messages', { params }).then((r) => r.data),
  saveMessage: (id, data) => apiClient.put(`/api/admin/messages/${id}`, data).then((r) => r.data),
  deleteMessage: (id) => apiClient.delete(`/api/admin/messages/${id}`),
  subscribers: (params) => apiClient.get('/api/admin/subscribers', { params }).then((r) => r.data),
  exportSubscribers: () => apiClient.get('/api/admin/subscribers/export', { responseType: 'blob' }).then((r) => r.data),
  deleteSubscriber: (id) => apiClient.delete(`/api/admin/subscribers/${id}`),
  existingContent: (type, params) => apiClient.get(`/api/admin/existing-content/${type}`, { params }).then((r) => r.data),
  adminUsers: () => apiClient.get('/api/admin/system/users').then(r => r.data),
  createAdminUser: data => apiClient.post('/api/admin/system/users', data).then(r => r.data),
  saveAdminUser: (id, data) => apiClient.put(`/api/admin/system/users/${id}`, data).then(r => r.data),
  resetAdminPassword: (id, newPassword) => apiClient.post(`/api/admin/system/users/${id}/reset-password`, { newPassword }),
  removeAdminAccess: id => apiClient.delete(`/api/admin/system/users/${id}`),
  permanentlyDeleteAdminUser: id => apiClient.delete(`/api/admin/system/users/${id}/permanent`),
  activityLog: params => apiClient.get('/api/admin/system/activity', { params }).then(r => r.data),
  activityUsers: () => apiClient.get('/api/admin/system/activity-users').then(r => r.data),
  activityFilters: () => apiClient.get('/api/admin/system/activity-filters').then(r => r.data),
  systemStatus: () => apiClient.get('/api/admin/system/status').then(r => r.data),
  seoIssues: () => apiClient.get('/api/admin/seo/issues').then(r => r.data),
  fixSafeSeoIssues: () => apiClient.post('/api/admin/seo/fix-safe').then(r => r.data),
  settings: () => apiClient.get('/api/admin/system/settings').then(r => r.data),
  saveSettings: data => apiClient.put('/api/admin/system/settings', data).then(r => r.data),
  newsArticle: (id) => apiClient.get(`/api/admin/news/${id}`).then((r) => r.data),
  createNewsArticle: (data) => apiClient.post('/api/admin/news', data).then((r) => r.data),
  saveNewsArticle: (id, data) => apiClient.put(`/api/admin/news/${id}`, data).then((r) => r.data),
  deleteNewsArticle: (id) => apiClient.delete(`/api/admin/news/${id}`),
  attachNewsGalleryMedia: (id, mediaAssetId) => apiClient.post(`/api/admin/news/${id}/gallery`, { mediaAssetId }).then((r) => r.data),
  setNewsThumbnail: (id, mediaAssetId) => apiClient.put(`/api/admin/news/${id}/gallery/${mediaAssetId}/thumbnail`).then((r) => r.data),
  reorderNewsGallery: (id, mediaAssetIds) => apiClient.put(`/api/admin/news/${id}/gallery/order`, { mediaAssetIds }).then((r) => r.data),
  detachNewsGalleryMedia: (id, mediaAssetId) => apiClient.delete(`/api/admin/news/${id}/gallery/${mediaAssetId}`).then((r) => r.data),
}
